####data preprocession####################
Test<-read.table("path_to/PSI_TEST",header = T)
express_Test <-read.table("path_to/FPKM_TEST",header = T)
annotation<-read.csv("gencode.v22.annotation.gene.probeMap",header=T,sep="\t")
names(annotation)[1]<- "Ensembl_ID"
merge(annotation,express_Test , by="Ensembl_ID")->gene_express_Test
colnames(gene_express_Test)<-gsub("\\.",'-',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-01A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-02A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-03A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-04A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-05A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-06A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-07A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-08A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-09A",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-01B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-02B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-03B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-04B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-05B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-06B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-07B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-08B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-09B",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-01C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-02C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-03C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-04C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-05C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-06C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-07C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-08C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-09C",'',     colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-11A",'-Norm',colnames(gene_express_Test))
colnames(gene_express_Test)<-gsub("-11B",'-Norm',colnames(gene_express_Test))
cancer=Test
cancer$mean <- apply(cancer[,-(1:10)],1,mean,na.rm=T)
cancer_filter<-subset(cancer,cancer$mean>0.05)
cancer_filter_sample <- apply(cancer_filter[,-c(1:10,ncol(cancer_filter))], 2, function(x){length(x[is.na(x)]) > nrow(cancer_filter) * 0.8})
cancer_filter_new <- cancer_filter[,colnames(cancer_filter[,-c(1:10,ncol(cancer_filter))])[!cancer_filter_sample]]
cancer_filter_new <-cbind(cancer_filter[,1:10],cancer_filter_new)
library(impute)
khan.imputed  <- impute.knn(as.matrix(cancer_filter_new[,-(1:10)]),k = 10,maxp = 1500, rng.seed=362436069)
output  <-khan.imputed  $data
K = cbind(cancer_filter_new[,1:10],output)
colnames(K )<-gsub("\\_",'-',colnames(K))
overlap<- Reduce(intersect, list(colnames(K ),colnames(gene_express_Test)))
overlap_AS<-cbind(K[,(1:10)],K[,overlap])
overlap_express<-cbind(gene_express_Test [,1],gene_express_Test [,overlap])
